### ISSUE TITLE
interaction with subword-mode

### ISSUE THREAD

**Issue by abred** [pmarinov/clean-aindent-mode#6]
Hi,

great mode :)

However I have a minor issue when using it in combination with subword-mode
M-DEL should delete the previous subword. Yet clean-aindent-mode overwrites this behavior and executes kill-word (if not in indent space).
I'm currently using this hack, but maybe there is a cleaner solution
```
-(kill-word (- arg))  ;; Original "C-backspace" key function
+(if subword-mode
+    (subword-kill (- arg))
+  (kill-word (- arg)))  ;; Original "C-backspace" key function
```

**Comment by pmarinov** [comment]
I'm glad you find it useful. I will take a look at a possible implementation tonight or tomorrow.

In the worst case, if there is no any nicer way, we can use your implementation with the added check about whether we have `subword-kill` available and then call it.

**Comment by abred** [comment]
is fixed in emacs 25
(word-boundary table is updated and the default commands are used)
